kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kube-diag
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080   # faultlab proxy NodePort
        hostPort: 30080
      - containerPort: 30090   # hub NodePort (local dev only)
        hostPort: 30090
